accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('schemas/', include('schemas.urls')),
]

schemas/urls.py
from django.urls import path
from . import views
from .views import ListSchemaView, CreateSchemaView

urlpatterns = [
    path('', ListSchemaView.as_view(), name='schema_list'),
    path('view/<int:id>/', views.SchemaView.as_view(), name='schema_view'),
    path('create/', CreateSchemaView.as_view(), name='schema_create'),
    path('edit/<int:id>/', views.edit_schema, name='schema_edit'),
    path('column/types/', views.get_columns_types, name='schema_column_types'),
]

accounts/models.py
from django.db import models

# Create your models here.

schemas/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Schema(models.Model):
    name = models.CharField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(default=datetime.now)
    modified = models.DateTimeField(default=datetime.now)

    class SeparatorType(models.TextChoices):
        COMMA = 'CM', _('Comma (,)')
        SEMICOLON = 'SM', _('Semicolon (;)')
        TAB = 'TB', _('Tab (\\t)')
        PIPE = 'PP', _('Pipe (|)')

    column_separator_type = models.CharField(
        max_length=2,
        db_index=True,
        choices=SeparatorType.choices,
        default=SeparatorType.COMMA,
    )

    class CharacterType(models.TextChoices):
        DOUBLE = 'DQ', _('Double quote (")')
        SINGLE = 'SQ', _('Single quote (\')')

    string_character_type = models.CharField(
        max_length=2,
        db_index=True,
        choices=CharacterType.choices,
        default=CharacterType.DOUBLE,
    )

    def __str__(self):
        return self.name


class ColumnTypes(models.Model):
    name = models.CharField(max_length=128)
    with_extra_from_to = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Column(models.Model):
    name = models.CharField(max_length=128)
    type = models.ForeignKey(ColumnTypes, on_delete=models.CASCADE, blank=True)
    with_extra_from_to = models.BooleanField(default=False)
    extra_from = models.PositiveIntegerField(blank=True)
    extra_to = models.PositiveIntegerField(blank=True)
    order = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class Dataset(models.Model):
    class StatusType(models.TextChoices):
        READY = 'RD', _('Ready')
        PROCESSING = 'PR', _('Processing')

    status_type = models.CharField(
        max_length=2,
        db_index=True,
        choices=StatusType.choices,
        default=StatusType.PROCESSING,
    )

    file = models.FileField(upload_to='schemas/%Y/%m/%d', blank=True)
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE, blank=True)
    created = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.status_type

schemas/forms.py
from django.forms import ModelForm
from.models import Schema, Dataset


class SchemaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SchemaForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Schema
        fields = ['name', 'column_separator_type', 'string_character_type', 'user']

accounts/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.contrib import messages, auth


@csrf_exempt
def login(request):
    if request.user.is_authenticated:
        return redirect('schema_list')

    if request.method == 'POST':
        # Get form data
        username = request.POST['username']
        password = request.POST['password']

        # Authenticate
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('schema_list')
        else:
            messages.error(request, 'Incorrect username or password')

    return render(request, 'accounts/login.html')


@csrf_exempt
def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
        messages.info(request, 'Logout done')

    return redirect('login')

schemas/views.py
import json

from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.core.serializers import serialize
from .models import Schema, Dataset, ColumnTypes
from .forms import SchemaForm
from django.views.generic import View, TemplateView


@method_decorator(login_required, name='dispatch')
class ListSchemaView(TemplateView):
    template_name = "schemas/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['schemas'] = Schema.objects.all()
        return context


@method_decorator(login_required, name='dispatch')
class CreateSchemaView(View):
    def get(self, request):
        form = SchemaForm()

        return render(request, 'schemas/create.html', {
            "form": form
        })

    def post(self, request):
        updated_data = request.POST.copy()
        updated_data.update({'user': request.user})

        form = SchemaForm(updated_data)
        # check whether it's valid:
        print(form.errors)
        if form.is_valid():

            form = form.save(commit=False)
            form.user = request.user
            form.save()

            return redirect('schema_list')

        return render(request, 'schemas/create.html', {
            "form": form
        })


@method_decorator(login_required, name='dispatch')
class SchemaView(View):
    def get(self, request, id):
        schema = Schema.objects.get(pk=id)
        datasets = Dataset.objects.filter(schema=schema).all()

        return render(request, 'schemas/view.html', {
            "datasets": datasets,
            'id': id
        })

    def post(self, request, id):
        schema = Schema.objects.get(pk=id)
        dataset = Dataset(schema=schema)
        dataset.save()

        return redirect('schema_view', id)


@csrf_exempt
def get_columns_types(request):
    types = ColumnTypes.objects.all()
    data = serialize("json", types, fields=('id', 'name'))

    return JsonResponse(json.loads(data), safe=False)


@login_required
@csrf_exempt
def edit_schema(request, id):
    return render(request, 'schemas/edit.html')

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center align-items-center" style="height:100vh">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <div class="row justify-content-center align-items-center">
                    <div class="col-6">
                        <form action="{% url 'login' %}" autocomplete="off" method="post">
                            <h1 style="text-align: center; margin: 3rem 0;">Login</h1>
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}" role="alert">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div class="form-group">
                                <input type="text" class="form-control" name="username" placeholder="Username">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="Password">
                            </div>
                            <div class="form-group" style="margin-bottom: 7rem">
                                <button type="submit" id="sendlogin" class="btn btn-primary float-right">Login</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fake CSV</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Top Bar -->
    {% if request.path != '/' and 'login' not in request.path %}
        {% include 'partials/_topbar.html' %}
    {% endif %}

    <!-- Main Content -->
    <div class="container">
        {% block content %} {% endblock %}
    </div>

</body>
</html>

templates/partials/_topbar.html
  <!-- Top Bar -->
  <section id="top-bar" class="p-3" style="background-color: #f2f2f2;">
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <h3>FakeCSV</h3>
        </div>
        <div class="col-md-3">
          <a href="{% url 'schema_list' %}">Schemas</a>
        </div>
        <div class="col-md-7" style="color: grey">
          <div class="social text-right">
              Hello, <b>{{ request.user.username }}</b>
            &nbsp;&nbsp;&nbsp;
            <a href="{% url 'logout' %}">
              Logout
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/schemas/create.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="row">
    <div class="col">
        <h2 class="float-left">New Schemas</h2>
        <a onclick="document.getElementById('schema_create').submit()" type="button"
           class="btn btn-success float-right">Submit</a>
    </div>
</div>

<div class="row">
    <div class="col">
        <form action="{% url 'schema_create' %}" method="post" id="schema_create">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name" class="form-label">Name</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="form-group">
                <label for="id_column_separator_type" class="form-label">Column separator</label>
                {{ form.column_separator_type }}
                {{ form.column_separator_type.errors }}
            </div>
            <div class="form-group">
                <label for="id_string_character_type" class="form-label">String character</label>
                {{ form.string_character_type }}
                {{ form.string_character_type.errors }}
            </div>

        </form>
    </div>
</div>
<div class="row">
    <div class="col">
        <h2 class="float-left">Schemas Columns</h2>
    </div>
</div>
<form>
    <div id="root_rows"></div>

<!--    <div class="form-row">-->
<!--        <div class="form-group col-md-3">-->
<!--            <input type="text" class="form-control" placeholder="First name">-->
<!--        </div>-->
<!--        <div class="form-group col-md-3">-->
<!--            <select class="form-control" aria-label="Default select example">-->
<!--                <option selected>String character</option>-->
<!--                <option value="1">One</option>-->
<!--                <option value="2">Two</option>-->
<!--                <option value="3">Three</option>-->
<!--            </select>-->
<!--        </div>-->
<!--        <div class="form-group col-md-3">-->

<!--        </div>-->
<!--        <div class="form-group col-md-3">-->
<!--            <input type="text" class="form-control" placeholder="Last name">-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="form-row">-->
<!--        <div class="form-group col-md-3">-->
<!--            <input type="text" class="form-control" placeholder="First name">-->
<!--        </div>-->
<!--        <div class="form-group col-md-3">-->
<!--            <select class="form-control" aria-label="Default select example">-->
<!--                <option selected>String character</option>-->
<!--                <option value="1">One</option>-->
<!--                <option value="2">Two</option>-->
<!--                <option value="3">Three</option>-->
<!--            </select>-->
<!--        </div>-->
<!--        <div class="form-row col-md-3">-->
<!--            <div class="form-group col-md-6">-->
<!--                <input type="text" class="form-control" placeholder="Last name">-->
<!--            </div>-->

<!--            <div class="form-group col-md-6">-->
<!--                <input type="text" class="form-control" placeholder="Last name">-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-group col-md-3">-->
<!--            <input type="text" class="form-control" placeholder="Last name">-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="form-row">-->
<!--        <div class="form-group col-md-3">-->
<!--            <input type="text" class="form-control" placeholder="First name">-->
<!--        </div>-->
<!--        <div class="form-group col-md-3">-->
<!--            <select class="form-control" aria-label="Default select example">-->
<!--                <option selected>String character</option>-->
<!--                <option value="1">One</option>-->
<!--                <option value="2">Two</option>-->
<!--                <option value="3">Three</option>-->
<!--            </select>-->
<!--        </div>-->
<!--        <div class="form-group col-md-3">-->
<!--        </div>-->
<!--        <div class="form-group col-md-3">-->
<!--            <input type="text" class="form-control" placeholder="Last name">-->
<!--        </div>-->
<!--    </div>-->
</form>

<script src="{% static 'js/reactify-django.ui.js' %}"></script>
{% endblock %}

templates/schemas/edit.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2 class="float-left">New Schemas</h2>
    <a href="{% url 'schema_list' %}" type="button" class="btn btn-success float-right">Submit</a>
</div>
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Email address</label>
  <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>
{% endblock %}

templates/schemas/list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col">
        <h2 class="float-left">Data Schemas</h2>
        <a href="{% url 'schema_create' %}" type="button" class="btn btn-success float-right">New Schema</a>
    </div>
</div>
<table class="table table-hover table-bordered caption-top">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Modified</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% if schemas %}
    {% for schema in schemas %}
    <tr>
        <th scope="row">{{ schema.id }}</th>
        <td><a href="{% url 'schema_view' schema.id %}">{{ schema.name }}</a></td>
        <td>{{ schema.modified }}</td>
        <td>
            <a href="{% url 'schema_edit' schema.id %}">Edit schema</a>
            &nbsp;&nbsp;&nbsp;
            <a href="javascript:;">Delete</a>
        </td>
    </tr>
    {% endfor %}

    {% else %}
    <caption>
        No schema yet!
    </caption>
    {% endif %}
    </tbody>
</table>
{% endblock %}

templates/schemas/view.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2 class="float-left">Data Sets</h2>

    <form action="{% url 'schema_view' id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success float-right">Generate Data</button>
    </form>

</div>
<table class="table table-hover table-bordered caption-top">
    <caption class="">

    </caption>
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Created</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% if datasets %}
    {% for d in datasets %}
    <tr>
        <th scope="row">{{ d.id }}</th>
        <td>{{ d.created }}</td>
        <td>
            {% if d.status_type == 'PR' %}
                <span class="badge badge-secondary">Processing</span>
            {% else %}
                <span class="badge badge-success">Ready</span>
            {% endif %}
        </td>
        <td>
        </td>
    </tr>
    {% endfor %}
    {% else %}
        <caption>No data sets yet!</caption>
    {% endif %}
    </tbody>
</table>
{% endblock %}